# postgres/redis test environment
version: '3.1'
services:
#  cerebot2:
#    build: .
#    restart: always
#    links:
#      - redis
#      - postgres
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: cerebot
      POSTGRES_PASSWORD: cerebot
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: