version: '3.5'
services:
  cerebot:
    build: .
    restart: always
    environment:
      CEREBOT_AUTH_TOKEN: '$CEREBOT_AUTH_TOKEN'
      CEREBOT_USERNAME: '$CEREBOT_USERNAME'
      DATABASE_URL: 'postgres://cerebot:${CEREBOT_DB_PASSWORD:-cerebot}@postgres:5432'
      REDIS_URL: 'redis:6379'
      RUST_LOG: '$RUST_LOG'
      RAPIDAPI_KEY: '$RAPIDAPI_KEY'
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:5-alpine
    volumes:
      - $HOME/cerebot2/redis:/data
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: '${CEREBOT_DB_USER:-cerebot}'
      POSTGRES_PASSWORD: '${CEREBOT_DB_PASSWORD:-cerebot}'
    ports:
      - 6432:5432
    volumes:
      - $HOME/cerebot2/postgres:/var/lib/postgresql/data