version: '3.5'
services:
  cerebot:
    build: .
    restart: always
    environment:
      CEREBOT_AUTH_TOKEN: '$CEREBOT_AUTH_TOKEN'
      CEREBOT_USERNAME: '$CEREBOT_USERNAME'
      DATABASE_URL: 'postgres://cerebot:${CEREBOT_DB_PASSWORD:-cerebot}@localhost:5432'
      REDIS_URL: '127.0.0.1:6379'
      RUST_LOG: ${RUST_LOG}
    links:
      - redis
      - postgres
  redis:
    image: redis:5-alpine
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: '${CEREBOT_DB_USER:-cerebot}'
      POSTGRES_PASSWORD: '${CEREBOT_DB_PASSWORD:-cerebot}'
    ports:
      - 6432:5432
    volumes:
      - $HOME/cerebot2-data:/var/lib/postgresql/data