[package]
name = "backend"
version = "0.1.0"
authors = ["cerebellum42 <cere@fastmail.fm>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
typescript-definitions = "=0.1.9"
typescript-definitions-derive = "=0.1.9"
serde = "1.0.104"